server:
  port: 7000

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/